name: Filter Group Solar CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/filter-group-solar-frontend:latest ./frontend

      - name: Push Frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/filter-group-solar-frontend:latest

      - name: Build Backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/filter-group-solar-backend:latest ./backend-new

      - name: Push Backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/filter-group-solar-backend:latest